# Generated by Django 3.2 on 2022-10-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
