# Generated by Django 3.2 on 2022-11-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221124_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='solicitud',
            new_name='consulta',
        ),
    ]
