# Generated by Django 3.2 on 2022-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
