# Generated by Django 3.2 on 2022-12-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart1_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart1',
        ),
    ]
