# Generated by Django 3.2 on 2022-12-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20221211_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='pedido_id',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
