# Generated by Django 3.2 on 2022-12-12 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20221211_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoConfirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['id'],
            },
        ),
    ]
