# Generated by Django 3.2 on 2022-12-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_cart_id_pedidoconfirmado_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
