# Generated by Django 3.2 on 2022-10-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='number',
        ),
    ]
