# Generated by Django 3.2 on 2022-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='with_discount',
            field=models.BooleanField(null=True,default=None),
            preserve_default=False,
        ),
    ]
